modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="starcatcher" #mandatory
version="0.10" #mandatory
displayName="Starcatcher" #mandatory
authors="wdiscute, Nikdo53" #optional
description='''A fishing mod with lots of fishes to collect!'''

[[dependencies.starcatcher]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.starcatcher]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
